<footer style="border-top: 1px solid #d5d5d5; font-size: .8em;">
	<ul style="font-family:'Helvetica', 'Arial', 'Sans-Serif';
			padding: 0px;
			list-style: none;
			font-weight: bold;">
   		<li style="display: inline; margin-right: 20px;">
			<a style="color: #999;" 
				href="mailto:carmim@gmail.com">email</a>
		</li>
  		<li style="display: inline; margin-right: 20px;">
			<a style="color: #999;"
				href="https://carmimerimovich.github.io/">Carmi Merimovich</a>
		</li>
        <li style="display: inline; margin-right: 20px;">
			<span style="color: #999;">
			Things
            </span>
		</li>
	</ul>
</footer>
